### ISSUE TITLE
Invalid conformance is accepted as valid

### ISSUE THREAD

**Issue by michelemottini** [onc-healthit/inferno#110]
The conformance statement returned by the https://greenfield-apis.meditech.com/v1/argonaut/v1 end point contains an invalid search parameter target:

```
       {
          "type": "Observation",
          "interaction": [
            { "code": "read" },
            { "code": "search-type" }
          ],
          "searchParam": [
            {
              "name": "patient",
              "definition": "http://www.fhir.org/guides/argonaut/r2/",
              "type": "reference",
              "documentation": "Search for all Observation resources for a patient",
              "target": [ "reference" ],
```
that is not flagged by the tests.

(This is a pretty bad problem because if you are using a library to access that server you are stuck: the library won't accept the conformance - and reading that is the very first thing you have to do)

**Comment by arscan** [comment]
Thanks @michelemottini -- I agree that this is important.  Errors in the Conformance/Capability are frequent and are killer for multi-purpose clients (as ours is).  

I finally worked through my backlog and have started to address this issue.  It seems like one of our underlying libraries needs to be updated, and once that is finished I'll get it through to this project.

**Comment by michelemottini** [comment]
Thanks @arscan 

Note that MEDITECH fixed their conformance statement, so the problem no longer reproduces against their end point

**Comment by arscan** [comment]
I did notice that as well -- I ended up mocking an example to replicate the issue.  I'll keep this open until the update makes it through to here (hopefully within a few days).  Thanks again!

**Comment by arscan** [comment]
Just a quick update since this has been sitting here for awhile -- we fixed the problem in the underlying library (in https://github.com/fhir-crucible/fhir_dstu2_models/pull/12) that prevented us from validating the conformance statement completely, and we'll be updating the test itself soon.

**Comment by radamson** [comment]
This issue hasn't had activity in a while and it looks like the issue has been fixed. Closing this, but feel free to reopen if there needs to be further discussion.
