### ISSUE TITLE
https://inferno.healthit.gov/inferno/bOhlG3KtlKE/strict/ - Conformance/Capability + typo

### ISSUE THREAD

**Issue by saulakravitz** [onc-healthit/inferno#186]
Last sentence confused me.   SHould it say: "This test refers to it as CONFORMANCE statement as that is what it was called in DSTU2."

accimidate-->accomodate

Here is what it was:
"The Conformance Statement Sequence tests a FHIR server’s ability to formally describe features supported by the API by using the Conformance Statement resource. The features described in the Conformance Statement must be consistent with the required capabilities of an Argonaut server. The Conformance Statement must also advertise the location of the required SMART on FHIR endpoints that enable authenticated access to the FHIR server resources.

Not all servers are expected to implement all possible queries and data elements described in the Argonaut API. For example, the Argonaut specification requires that the Patient resource and only one other Argonaut resource are required. Implementing the Conformance Statement resource allows clients to dynamically determine which of these resources are supported at runtime, instead of having to specifically write the application to *accomidate* every known server implementation at development time. Similarly, by providing information about the location of SMART on FHIR OAuth 2.0 endpoints, the client does not have to be hard-coded with information about the authorization services associated with every FHIR API.

Note that the name of this resource changed to ‘Capability Statement’ in STU3 to better describe the intent of this resource. This test refers to it as the Capability Statement as that is what it was called in DSTU2."

**Comment by radamson** [comment]
Thanks for the report!

I created a PR to clean up and update the details: https://github.com/onc-healthit/inferno/pull/307
