### ISSUE TITLE
Medication read resource supported

### ISSUE THREAD

**Issue by tarunkumar985** [onc-healthit/inferno#238]
Hi,

i have verified on HL7 site there is no relation between patient and medication. then why you are using patient as a parameter.
![2](https://user-images.githubusercontent.com/42908566/60721688-5e4dd200-9f4c-11e9-9cac-cdea8c75eff3.JPG)

**Comment by arscan** [comment]
Thanks for the report.  You are correct, this is an incorrect query.  We will likely remove this test and have these profiles be checked during the other medication-related tests that do have a patient search parameter and reference Medication resources, which is how our DSTU2-related tests work.

FYI @czh-orz 

Note no search parameters are required:
https://www.hl7.org/fhir/us/core/StructureDefinition-us-core-medication.html

**Comment by czh-orz** [comment]
The sequence has been updated so that Medication does not perform any searches. Thanks for the report!
