### ISSUE TITLE
Tools says CRUD methods not supported based on conformance statement, but they are

### ISSUE THREAD

**Issue by darena-mhaque** [onc-healthit/inferno#259]
I am using the online tool with R4.

The tool says that the various CRUD operations are not supported because it was not stated in the conformance statement. Here is an example from the CareTeam resource:

![image](https://user-images.githubusercontent.com/45796503/61960212-12161080-af93-11e9-98e1-8d4679d1ddca.png)

Here is our FHIR server's conformance statement: https://fhir-staging.bluebuttonpro.com/myhealth-r4/metadata 

Using the CareTeam resource, we can clearly see that the conformance statement indicates all CRUD operations are supported:

![image](https://user-images.githubusercontent.com/45796503/61960356-4b4e8080-af93-11e9-94f9-2e1dd8047f00.png)

This same error is being displayed in several other resources in the tool. Here are the following:

- DiagnosticReport (Note)
  - States that create operations are not supported
- DocumentReference
  - States create operations are not supported
- MedicationRequest
  - States that read operations are not supported
  - States that vread operations are not supported
  - States that history operations are not supported
  - States that search operations are not supported

**Comment by czh-orz** [comment]
Hi, 

Thanks for bringing this up. The issue has been resolved in our development branch and will be reflected in the reference site soon.

Thanks, 
Chase

**Comment by Jammjammjamm** [comment]
This was addressed by #254.
