### ISSUE TITLE
Onset-date not set for Condition resource data access

### ISSUE THREAD

**Issue by darena-mhaque** [onc-healthit/inferno#260]
I am using the online tool for R4.

In the Condition resource data access test, the onset-date is not being set. Our server is generating a bad request. The inferno tool should provide a value for the `onset-date` search parameter regardless. I'm not aware of a rule that says the value does not have to be provided and that a default value can be used. If there is one, please let me know.

This is the request being made with the `onset-date` search parameter, but no value being set:

![image](https://user-images.githubusercontent.com/45796503/61960940-87ceac00-af94-11e9-8afb-76c2f0023c56.png)

**Comment by radamson** [comment]
Thanks for the report!  We're making updates to how we test search parameters that should address this issue: https://github.com/onc-healthit/inferno/pull/239.  Once it's stable we'd love to have you try it out to make sure it works with your server.

**Comment by czh-orz** [comment]
Thanks for the report. This was happening because the Condition resource returned from the first search didn't contain an onset-date. The test has  been updated to skip unless the onset-date has been set.
