### ISSUE TITLE
Fatal Error: undefined method `coding' for #<Array:0x00007fa6c7bbee80>

### ISSUE THREAD

**Issue by darena-mhaque** [onc-healthit/inferno#262]
I am using the online tool for R4.

I am receiving this error: `Fatal Error: undefined method 'coding' for #<Array:0x00007fa6c7bbee80>`

I am not sure exactly why. Here is a screenshot of the request:

![image](https://user-images.githubusercontent.com/45796503/61961308-34a92900-af95-11e9-8925-05b66218f005.png)

Here is the response body our server generated:

```json
{
  "resourceType": "Bundle",
  "type": "searchset",
  "total": 1,
  "entry": [
    {
      "fullUrl": "https://fhir-staging.bluebuttonpro.com/myhealth-r4/DiagnosticReport/5d3a089b72e89ba0945a1ec2",
      "resource": {
        "resourceType": "DiagnosticReport",
        "id": "5d3a089b72e89ba0945a1ec2",
        "meta": {
          "versionId": "1",
          "lastUpdated": "2019-07-25T19:53:01.253+00:00"
        },
        "identifier": [
          {
            "system": "http://terminology.bluebuttonpro.com/identifier",
            "value": "6e111e681224433592ac6baa5a451b68_5d3a089b72e89ba0945a1ec2"
          }
        ],
        "status": "unknown",
        "category": [
          {
            "coding": [
              {
                "system": "http://terminology.hl7.org/CodeSystem/v2-0074",
                "code": "LAB"
              }
            ]
          }
        ],
        "code": {
          "coding": [
            {
              "system": "http://loinc.org",
              "code": "11134-4",
              "display": "Appearance of Spun Body fluid"
            }
          ]
        },
        "subject": {
          "reference": "Patient/5d3a089b72e89ba0945a1ea9"
        },
        "effectiveDateTime": "2019-04-07T21:43:14.0000000Z",
        "issued": "2018-08-14T22:59:48+00:00"
      },
      "response": {
        "lastModified": "2019-07-25T19:53:01.253+00:00"
      }
    }
  ]
}
```

This is only happening for the `DiagnosticReport` (Lab) resource. The error occurs on Test numbers 2, 4, and 8.

**Comment by czh-orz** [comment]
Hi, 

This issue has been resolved in our development branch and will be reflected in the reference website soon. 

Thanks, 
Chase

**Comment by radamson** [comment]
We just released a new version on GitHub and to the website that addresses this.  Would you take a look and let us know if it resolves your issue?

**Comment by darena-mhaque** [comment]
I apologize for getting to this so late, but we had taken a small break from this project. We are recently starting again. I have verified this has been corrected. This issue can be closed.
