### ISSUE TITLE
Fatal error: undefined method `validate_create_reply'

### ISSUE THREAD

**Issue by darena-mhaque** [onc-healthit/inferno#357]
**Subject of the issue**
A fatal error occurs for DiagnosticReport test number 9:
![image](https://user-images.githubusercontent.com/45796503/69185670-2dc69900-0ae5-11ea-84a3-665d07b43c24.png)

This issue also occurs for the following resource tests:
- DiagnosticReport for Laboratory Results Reporting Tests
- DocumentReference

Here is our server's metadata: [https://fhir-staging.bluebuttonpro.com/example/metadata](https://fhir-staging.bluebuttonpro.com/example/metadata). This indicates we do support create:

![image](https://user-images.githubusercontent.com/45796503/69186054-d5dc6200-0ae5-11ea-8842-673196f4811a.png)

**Your environment**
* Edition of inferno (Community or Program): Community
* Version of inferno: 2.7.0
* Which browser and version(s) is the bug present on?: Firefox v70.0.1

**Comment by Jammjammjamm** [comment]
The most recent US Core update added requirements for the `create` interaction. Inferno automatically generates tests based on US Core, but doesn't yet have support for `create` tests. This failure can be ignored and should be fixed in the next release.

**Comment by Jammjammjamm** [comment]
This was addressed in #362.
