### ISSUE TITLE
Broken link to dedicated HL7 FHIR chat channel

### ISSUE THREAD

**Issue by lmsurpre** [onc-healthit/inferno#444]
When I click on the link at https://github.com/onc-healthit/inferno#contact-us it takes me to a zulip page that says:

"This stream does not exist or is private."

Is there a new name for the stream?

**Comment by arscan** [comment]
Hmm, strange, not sure why that link would have changed.  Could you try out this link: https://chat.fhir.org/#narrow/stream/179309-inferno

**Comment by lmsurpre** [comment]
that one works, thanks

**Comment by radamson** [comment]
@lmsurpre Thanks for submitting the fix for this!  I'm going to close this issue as that PR resolved it, but if it turns out there is still a problem we can reopen it.
