### ISSUE TITLE
US Core smoking status patient+category+date search (USCSSO-03) should be optional

### ISSUE THREAD

**Issue by weiyuzh** [onc-healthit/inferno#447]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
USCSSO-03 is currently a required test for looking up smoking status via Observation search by patient+category+date. However, date is not a mandatory search parameter per the US Core smoking status profile. As such, USCSSO-03 should be an optional test for US Core v3.1.0 compliance rather than a required test.

**Your environment**
* Edition of inferno (Community or Program): Community
* Version of inferno: 2.9.0

**Comment by yunwwang** [comment]
The required search parameter combinations are listed in US Core v3.1.10 Section 7.1.1.2.14 (https://www.hl7.org/fhir/us/core/CapabilityStatement-us-core-server.html#observation)
```
SHALL | patient+category+date | reference+token+date | GET [base]/Observation?patient=[patient]&category=[system]\|[code]&date=[date]
```

**Comment by weiyuzh** [comment]
Thanks for sharing that reference! I was under the impression that the capabilitystatement narrative is listing a superset of required search parameters (based on all profiles on observation) (for smoking status, I'm not sure what the value of searching on patient+category is, considering all the other codes that can fall into the social-history category), and that the smoking status profile itself is the only profile defining required search parameters.

That being said, I don't see anything explicit to support my interpretation. I started a chain on zulip to get some further clarification:

https://chat.fhir.org/#narrow/stream/179166-implementers/topic/US.20core.20smoking.20status.20search.20parameters

**Comment by yunwwang** [comment]
This has been fixed
