### ISSUE TITLE
Support for versioned canonicals in CapabilityStatement

### ISSUE THREAD

**Issue by lmsurpre** [onc-healthit/inferno#451]
**CapabilityStatement**
I ran the CapabilityStatement tests and got a series of warnings on C-05:
```
CapabilityStatement does not claim support for US Core Location profile: http://hl7.org/fhir/us/core/StructureDefinition/us-core-location
CapabilityStatement does not claim support for US Core Observation profile: http://hl7.org/fhir/us/core/StructureDefinition/pediatric-bmi-for-age
CapabilityStatement does not claim support for US Core PractitionerRole profile: http://hl7.org/fhir/us/core/StructureDefinition/us-core-practitionerrole
...
```

However, when I check our CapabilityStatement, it does seem to include these.
For example, for the Location resource type:
```
                {
                    "type": "Location",
                    "profile": "http://hl7.org/fhir/profiles/Location",
                    "supportedProfile": [
                        "http://hl7.org/fhir/us/core/StructureDefinition/us-core-location|3.1.0"
                    ],
                    "interaction": [
                        {
                            "code": "create"
                        },
                        ...
```

**Your environment**
* Edition of inferno (Community or Program):  Community
* Version of inferno:  0.9.2 
* Which browser and version(s) is the bug present on?:  All

**Steps to reproduce**
1. Set up a CapabilityStatement that claims support for the US Core profiles with a specific version in the canonical reference (e.g. `http://hl7.org/fhir/us/core/StructureDefinition/us-core-location|3.1.0`)
2. Execute the US Core tests for Capability Statement and check the results for C-05

**Expected behavior**
The tests pass with no warning

**Actual behavior**
```CapabilityStatement does not claim support for US Core Location profile: http://hl7.org/fhir/us/core/StructureDefinition/us-core-location```

**Comment by radamson** [comment]
Thanks for submitting this issue!  We're working on a fix and will let you know when it's out if you'd like to test it again.

Relevant FHIR chat for future reference here: https://chat.fhir.org/#narrow/stream/179309-inferno/topic/Support.20for.20versioned.20canonicals.20in.20CapabilityStatement

**Comment by yunwwang** [comment]
This issue has been addressed
