### ISSUE TITLE
Date search parameters are treated as datetime when performing date range searches

### ISSUE THREAD

**Issue by weiyuzh** [onc-healthit/inferno#457]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
For US Core test cases involving date search parameters, the test usually involves:
- grabbing a datetime value from a previous response (e.g. Encounter.period)
- adding comparators (gt/ge/lt/le) 
- shifting the date value +1/-1 for inclusion purposes
- send query back to FHIR server to ensure date parameter is respected

This is fine when the datetime element in the previous response is a date+time. However, when the element is date only, the date search parameter calculation does a date only->datetime conversion.

For example:
- In USCE-02/patient encounter search, FHIR server returns an encounter resource where encounter.period.start = 2020-05-26, encounter.period.end = 2020-05-26.
- In USCE-04/patient+date encounter search, after the [initial gt search for gt2020-05-26](https://github.com/onc-healthit/inferno/blob/aef309b33045cabd4a4096133068143becceb7ef/lib/modules/uscore_v3.1.0/us_core_encounter_sequence.rb#L161), the subsequent [gt/lt/le/ge searches](https://github.com/onc-healthit/inferno/blob/aef309b33045cabd4a4096133068143becceb7ef/lib/modules/uscore_v3.1.0/us_core_encounter_sequence.rb#L165-L170) are using datetime precision (gt2020-05-26T00:00:00+00:00).

The subsequent searches assumes that 2020-05-26 is equivalent with 2020-05-26T00:00:00 GMT, which may vary based on server time zone. This is caused by the date +1/-1 shift in [date_comparator_value](https://github.com/onc-healthit/inferno/blob/aef309b33045cabd4a4096133068143becceb7ef/lib/app/sequence_base.rb#L763-L774). 

Expected behavior: when the source element is a date only element, perform subsequent date-based searches with date only values as well (i.e. date_comparator_value should return date-only if the input is date-only, and datetimes only if the input is a datetime).

Additionally, [get_value_for_search_param](https://github.com/onc-healthit/inferno/blob/aef309b33045cabd4a4096133068143becceb7ef/lib/app/sequence_base.rb#L740-L745) uses gt/lt when determining search parameter values based on periods in previous responses. This may exclude valid results:

For example:
- In USCE-02/patient encounter search, FHIR server returns a single encounter resource where encounter.period.start = 2020-05-26, encounter.period.end = 2020-05-26.
- In USCE-04/patient+date encounter search, the test case will return no results because the first date parameter search will be gt2020-05-26. Since the sole encounter is on 2020-05-26, the FHIR server will return no results.

Expected behavior: get_value_for_search_param should use ge/le comparators rather than gt/lt comparators.

**Your environment**
* Edition of inferno (Community or Program): Community
* Version of inferno: 2.9.0
* Which browser and version(s) is the bug present on?: Chrome 81.0.4044.138 (but this isn't browser specific)
* The selected test suite: US Core v3.1.0

**Comment by czh-orz** [comment]
Thanks for reporting this issue! It does look like a bug in our system where we were incorrectly determining the search parameter for the resource. We will work to resolve this issue soon.

**Comment by yunwwang** [comment]
fix was released in v2.10.0
