### ISSUE TITLE
CareTeam Tests require a status of "proposed"

### ISSUE THREAD

**Issue by fhirczar** [onc-healthit/inferno#458]
CareTeam Tests require a status of "proposed"
The USCCT-02 test is requiring us to support a status of "proposed."  Currently our system supports a status both "active" and "inactive."  When the it performs a search by patient+status (of proposed) it results in a 204 No Content (which is correct) and then skips over all the remaining tests.  

**Your environment**
* Edition of inferno (Community or Program): Community.
* Version of inferno: 2.9.0
* Which browser and version(s) is the bug present on?: Chrome 83.0.4103.61

**Steps to reproduce**
Steps to reproduce should not be necessary since the test is hard coded to use a status of "proposed."

**Expected behavior**
This test either needs to search by "active" (which all systems would support) or it needs to skip over "proposed" (if there are no results) and then search by "active" so it doesn't result in a 204 No Content and then fail all the remaining tests.  We do not want to add a status of "proposed" and no where in the FHIR spec does it indicate we must support this status.

**Actual behavior**
The USCCT-02 test is requiring us to support a status of "proposed."  Currently our system supports a status both "active" and "inactive."  When the it performs a search by patient+status (of proposed) it results in a 204 No Content (which is correct) and then skips over all the remaining tests.  See screenshot.

![USCCT-02 Test](https://user-images.githubusercontent.com/66029960/83906234-d9090980-a728-11ea-8b1e-a40f2fb3a5f7.PNG)

**Comment by radamson** [comment]
[The FHIR spec section on search](https://www.hl7.org/fhir/http.html#search) indicates that:

> If the search succeeds, the server SHALL return a 200 OK HTTP status code and the return content SHALL be a Bundle with type = searchset containing the results of the search as a collection of zero or more resources in a defined order.

**Note:** this includes situations where you perform a search and have no matching resources (`zero or more resources`).

> If the search fails (cannot be executed, not that there are no matches), the return value return value SHALL be a status code 4xx or 5xx with an OperationOutcome.

Thus instead of `204 No Content` a client would expect to receive a `200 OK` with no results. Based on the current choice of `204 No Content` it sounds like this would apply.

If the server truly cannot execute this search then a relevant 4XX or 5XX status code should be returned.

**Comment by fhirczar** [comment]
Thank you for the quick response.  We have applied the suggested change and are not passing all the expected Inferno tests.

**Comment by arscan** [comment]
Since you closed the issue, I assume you meant to say "are now passing"?

**Comment by fhirczar** [comment]
Sorry, that was a typo.  We are now passing the expected Inferno tests.
