### ISSUE TITLE
Fatal Error on the Organization Provenance

### ISSUE THREAD

**Issue by healthland** [onc-healthit/inferno#460]
Subject:  Fatal Error on Organization Provenance

We have received this Fatal Error:
 USCO-09: All must support elements are provided in the Organization resources returned. results...
Details: Fatal Error: undefined method `identifier' for #<FHIR::Provenance:0x00007f7b8b780498 @id="2", @meta=nil, @implicitRules=nil, @language=nil, @text=nil, @contained=[], @extension=[], @modifierExtension=[], @target=[#<FHIR::Reference:0x00007f7b8b77f818 @id=nil, @extension=[], @reference="Organization/2", @type=nil, @identifier=nil, @display=nil>], @occurredPeriod=nil, @occurredDateTime=nil, @recorded="2020-03-18T17:47:51.37-05:00", @policy=[], @location=nil, @reason=[], @activity=nil, @agent=[#<FHIR::Provenance::Agent:0x00007f7b8b77f368 @id=nil, @extension=[], @modifierExtension=[], @type=#<FHIR::CodeableConcept:0x00007f7b8b77ee18 @id=nil, @extension=[], @coding=[#<FHIR::Coding:0x00007f7b8b77eb20 @id=nil, @extension=[], @system="http://terminology.hl7.org/CodeSystem/provenance-participant-type", @version=nil, @code="enterer", @display=nil, @userSelected=nil>], @text=nil>, @role=[], @who=#<FHIR::Reference:0x00007f7b8b77e620 @id=nil, @extension=[], @reference="Practitioner/667", @type=nil, @identifier=nil, @display=nil>, @onBehalfOf=#<FHIR::Reference:0x00007f7b8b77e300 @id=nil, @extension=[], @reference="Organization/2", @type=nil, @identifier=nil, @display=nil>>], @entity=[], @signature=[]>

**Steps to reproduce**

- Using the url, https://inferno.healthit.gov/community

- click on US Core v3.1.0 and use this url: https://inferno.healthit.gov/community and click Begin

- Click on Run for the Organization Tests with valid token 

- Receive the above error

Include:

* The selected test suite is Organization
* The URL of the FHIR server being tested is https://rqhandler-dev.cpsi.com/primary/requesthandler/fhir/R4/
* The Test ID is USCO-09

**Expected behavior**
Pass Test

**Actual behavior**
! USCO-09: All must support elements are provided in the Organization resources returned. results...
Details: Fatal Error: undefined method `identifier' for #<FHIR::Provenance:0x00007f7b8b780498 @id="2", @meta=nil, @implicitRules=nil, @language=nil, @text=nil, @contained=[], @extension=[], @modifierExtension=[], @target=[#<FHIR::Reference:0x00007f7b8b77f818 @id=nil, @extension=[], @reference="Organization/2", @type=nil, @identifier=nil, @display=nil>], @occurredPeriod=nil, @occurredDateTime=nil, @recorded="2020-03-18T17:47:51.37-05:00", @policy=[], @location=nil, @reason=[], @activity=nil, @agent=[#<FHIR::Provenance::Agent:0x00007f7b8b77f368 @id=nil, @extension=[], @modifierExtension=[], @type=#<FHIR::CodeableConcept:0x00007f7b8b77ee18 @id=nil, @extension=[], @coding=[#<FHIR::Coding:0x00007f7b8b77eb20 @id=nil, @extension=[], @system="http://terminology.hl7.org/CodeSystem/provenance-participant-type", @version=nil, @code="enterer", @display=nil, @userSelected=nil>], @text=nil>, @role=[], @who=#<FHIR::Reference:0x00007f7b8b77e620 @id=nil, @extension=[], @reference="Practitioner/667", @type=nil, @identifier=nil, @display=nil>, @onBehalfOf=#<FHIR::Reference:0x00007f7b8b77e300 @id=nil, @extension=[], @reference="Organization/2", @type=nil, @identifier=nil, @display=nil>>], @entity=[], @signature=[]>

**Comment by yunwwang** [comment]
Hello healthland: 

USCO-09 is a test case for US Core Organization resources. I don't know why the resource logged was a Provenance resource. Do you mind to send the saved test session? To save a test session, you can click the "Save" button on the top right corner.

Thank you.

Thank you.

**Comment by healthland** [comment]
Thank you!  It looks like the fatal error has cleared up and the only error left is with the identifier system.  This is the saved test session.  https://inferno.healthit.gov/community/imHl73xBZEa/

**Comment by healthland** [comment]
I was wondering if for this the NPI or CLIA is also requried?

**Comment by yunwwang** [comment]
Yes. That is correct. According to https://www.hl7.org/fhir/us/core/StructureDefinition-us-core-organization.html, Organization must support identifiers with NPI and CLIA. This means all Organization resources on EHR server, as a collection, must have NPI identifier and CLIA identifier.

**Comment by healthland** [comment]
Thank you for your quick response.  I think this ticket is taken care of and we appreciate all your help!
