### ISSUE TITLE
SLS-08 should allow unrequested scopes

### ISSUE THREAD

**Issue by lmsurpre** [onc-healthit/inferno#464]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
I was testing smart app launch with a new identity server and I found that it is including an unrequested scope in its token response. I think this is permitted (per https://tools.ietf.org/html/rfc6749 at least), but it causes Inferno to mark the test failed:

> Token response contained unrequested scopes: <bad_scope_here>

The error is in:
`SLS-08: Token exchange response body contains required information encoded in JSON`

**Your environment**
* Edition of inferno (Community or Program): Community
* Version of inferno: 2.9.0
* Which browser and version(s) is the bug present on?: All

**Steps to reproduce**
* The selected test suite:  SMART Application Launch Framework Implementation Guide v1.0.0
* The URL of the FHIR server being tested:  localhost
* The Test ID, if it's a problem with a specific test:  SLS-08
* Any required configuration options (client ID, client secret, etc.): N/A
* Anything else needed to make the issue occur:  an authorization server that returns one or more extra claim in the access token it provides

**Expected behavior**
OAuth allows servers to return claims which do not match the requested claims from the client.

From https://tools.ietf.org/html/rfc6749
```
   The authorization server MAY fully or partially ignore the scope
   requested by the client, based on the authorization server policy or
   the resource owner's instructions.  If the issued access token scope
   is different from the one requested by the client, the authorization
   server MUST include the "scope" response parameter to inform the
   client of the actual scope granted.
```

I do think it makes sense to verify that the authorization server is able to provide at least some of the requested scopes, but it shouldn't fail the test if it decides to include additional ones.

Maybe it can also enforce the presence of `scope` in the response in cases where it doesn't match the request?

**Actual behavior**
It checks that "scope must be a strict subset of the requested scopes, or empty" and otherwise fails the test.

**Note**
Later in the tests, it checks that the refresh token contains a strict subset of the original scopes granted.  Please double-check these changes won't break that test (or similar ones) as well.

**Comment by radamson** [comment]
Thanks for reporting this issue @lmsurpre !  The team has discussed this and it does appear to be a bug.  This check should only happen during token refresh where the [scopes provided must be a strict sub-set of the scopes granted in the original launch](http://www.hl7.org/fhir/smart-app-launch/index.html#step-5-later-app-uses-a-refresh-token-to-obtain-a-new-access-token).  As you pointed out, this requirement does not apply to the initial token exchange.

We'll work on a fix!

Internal JIRA ticket: FI-891
[Relevant chat.fhir.org conversation here](https://chat.fhir.org/#narrow/stream/179309-inferno/topic/unrequested.20scope.20fails.20touchstone)
Related Issue: https://github.com/onc-healthit/inferno/issues/245

**Comment by yunwwang** [comment]
fix has been released
