### ISSUE TITLE
Issue with tests on urls that are valid and passed before or gave warning

### ISSUE THREAD

**Issue by healthland** [onc-healthit/inferno#486]
https://inferno.healthit.gov/community/c8ezsf4EJ31/  This is the saved test for 2 tests Encounter and Allergy Intolerance.  These had passed on 08/18/2020, but then later in the week started getting does not resolve errors and does not pass.  Some of these are urls used in the Core examples, others are personal urls that were just getting warnings before.

**Comment by yunwwang** [comment]
This is a known issue with HL7 validator. We already have a solution.
https://github.com/onc-healthit/inferno/pull/502

**Comment by healthland** [comment]
Thank you!

**Comment by healthland** [comment]
https://inferno.healthit.gov/community/1fjo6jIl3ns/

This is an error we are seeing still on the extensions.  Please let us know what we need to do to pass.  Thanks!

**Comment by healthland** [comment]
Thanks for the update.  This is working now.
