### ISSUE TITLE
MedicationRequest Tests invalid request when using medicationrequest.medication,.ofType(CodeableConcept) with url http://www.nlm.nih.gov/research/umls/rxnorm

### ISSUE THREAD

**Issue by healthland** [onc-healthit/inferno#501]
The US Core MedicationRequest shows the url, http://www.nlm.nih.gov/research/umls/rxnorm as valid.  https://build.fhir.org/ig/HL7/US-Core-R4/StructureDefinition-us-core-medicationrequest.html

URI for test instance:  https://inferno.healthit.gov/community/czMBXFXMU6y/

**Comment by yunwwang** [comment]
This is a known HL7 validator issue. We will find a solution for .this

**Comment by healthland** [comment]
Thank you!

**Comment by healthland** [comment]
https://inferno.healthit.gov/community/gag3VERT1Y6/

We are still seeing this issue on Community when testing.

**Comment by yunwwang** [comment]
It takes longer than expected. We hope to get this done before Connectathon.

**Comment by healthland** [comment]
Thank you for that update.

**Comment by healthland** [comment]
Thanks for the update this is working now.
