### ISSUE TITLE
Patient test failing when code 2131-1 Other Race is used for race.  

### ISSUE THREAD

**Issue by healthland** [onc-healthit/inferno#513]
This is the link that shows that patient fails when code 2131-1 is used for race, then if changed to 2106-3 it passes.  
https://inferno.healthit.gov/community/6wtqea8rkX7/

HL7 race codes: https://www.hl7.org/fhir/v3/Race/cs.html

**Comment by radamson** [comment]
It looks like you are referring to the [`us-core-race` extension](https://www.hl7.org/fhir/us/core/StructureDefinition-us-core-race.html) on the [US Core Patient](https://www.hl7.org/fhir/us/core/StructureDefinition-us-core-patient.html).

The `ombCategory` extension, which you have set as `2106-3 | White` in your example is not bound to [v3 Code System Race](https://www.hl7.org/fhir/v3/Race/cs.html).  It is bound to [OMB Race Categories](https://www.hl7.org/fhir/us/core/ValueSet-omb-race-category.html). This is a required binding and the ValueSet contains exactly 7 concepts, not including `2131-1`.

**Comment by healthland** [comment]
Thank you! This is very helpful to know.

**Comment by radamson** [comment]
No problem, happy to help! I'm going to close this issue, but feel free to reopen it if you have any other questions on it.
