### ISSUE TITLE
Patient validation for the Patient.communication.language error.  "Invalid Patient: Patient.communication[0].language: Unable to resolve value set "http://hl7.org/fhir/ValueSet/languages|4.5.0""

### ISSUE THREAD

**Issue by healthland** [onc-healthit/inferno#520]
https://inferno.healthit.gov/community/hHf2FoFZON9/  This was passing in December, but seems to be failing now.

**Comment by yunwwang** [comment]
This issue should be addressed by https://github.com/inferno-community/fhir-validator-app/issues/44. Please re run your tests

**Comment by healthland** [comment]
Thank you!  This is passing now.
