### ISSUE TITLE
Device.type: This property must be an Array, not an Object 

### ISSUE THREAD

**Issue by healthland** [onc-healthit/inferno#521]
https://inferno.healthit.gov/community/7e1Oh9TNtjt/  
This is on Community.  The device.type looks the same as the example given on Core, https://build.fhir.org/ig/HL7/US-Core-R4/Device-udi-3.json.html.

**Comment by yunwwang** [comment]
duplicated as issue #523

**Comment by healthland** [comment]
Thank you!  It is working again.
