### ISSUE TITLE
Encounter status 'finished' and 'arrived' not in value set and Encounter.type[0].coding[0].system: URL value 'http://www.ama-assn.org/go/cpt' does not resolve

### ISSUE THREAD

**Issue by healthland** [onc-healthit/inferno#522]
https://inferno.healthit.gov/community/3qDof2M8OVT/   for the status 'finished' not in value set.  Also, Encounter.type[0].coding[0].system: URL value 'http://www.ama-assn.org/go/cpt' does not resolve. 

https://inferno.healthit.gov/community/iBnqbEJitvW/     for the status 'arrived' not in value set.   Also, Encounter.type[0].coding[0].system: URL value 'http://www.ama-assn.org/go/cpt' does not resolve. 

The arrived and finished are part of the codes allowed for encounter-status, http://hl7.org/fhir/R4/valueset-encounter-status.html.

**Comment by yunwwang** [comment]
This should be resolved now. It is the same as https://github.com/inferno-community/fhir-validator-app/issues/44

**Comment by healthland** [comment]
Thank you!  I will retest.
