### ISSUE TITLE
Encounter error, Encounter.type[0].coding[0].system: URL value 'http://www.ama-assn.org/go/cpt' does not resolve

### ISSUE THREAD

**Issue by healthland** [onc-healthit/inferno#524]
https://inferno.healthit.gov/community/2mcDO4nBjYT/

The encounter.type.coding.system url value  'http://www.ama-assn.org/go/cpt' does not resolve.  

Include all codes defined in http://www.ama-assn.org/go/cpt

And this example shows this system being used.  https://build.fhir.org/ig/HL7/US-Core-R4/Encounter-example-1.json.html

**Comment by yunwwang** [comment]
The validator used by Inferno Community depends on tx.fhir.org as terminology server. tx.fhir.org does not support CPT code system yet. All supported code systems are listed at http://tx.fhir.org/r4/
PR #502 suppresses this error message

**Comment by healthland** [comment]
Thank you!  Looking forward to seeing PR #502 resolved.  Thanks for your quick response.

**Comment by healthland** [comment]
Thanks for the update.  This is working now.
