### ISSUE TITLE
Inferno server crashing frequently from database issues

### ISSUE THREAD

**Issue by nathanloyer** [onc-healthit/inferno#566]
**Subject of the issue**

We maintain an inferno deployment in AWS that many teams in our company can use to validate the FHIR resources they are working on. In the latest versions of inferno, we get errors related to accessing the database every 10-15 minutes when people are actively using it. It appears to be an issue with not maintaining database locks or releasing them correctly. I'm assuming this issue was introduced when the switch to ActiveRecord was made. I've noticed that we don't have this issue in Inferno Program Edition.

**Your environment**
* Edition of inferno (Community or Program): Community
* Version of inferno: 2.12 and latest/main
* Which browser and version(s) is the bug present on?: Latest Chrome version as of 5/24/2021

Our deployment uses the docker images you are publishing to docker hub, then we copy in our configuration files, custom internal certificates needed to auth with internal endpoints, terminology validators, and some custom modules that we have written. We then publish this docker image to our internal artifactory and deploy it as an ECS service in AWS.

**Steps to reproduce**

Usually after running the US Core v3.1.1 2 to 6 times the inferno server restarts and the error logs that are attached are available. I've been reproducing by running the entire US Core test suite.

* The selected test suite: **US Core 3.1.1**
* The URL of the FHIR server being tested: **This is an internal server for our company that you don't have access to.**
* The Test ID, if it's a problem with a specific test.: **Doesn't seem to be related to a specific test.**

**Expected behavior**

We should be able to keep our inferno service deployed and have it stay online for months, instead it is crashing after a few minutes when it is being used.

**Actual behavior**

With version 2.12 I get this error:

[logs1.txt](https://github.com/onc-healthit/inferno/files/6534347/logs1.txt)

I tried working around this by updating the settings on the db config yaml file to increase the number of connections and timeout, but I got the error message below instead. I also tried updating to the latest tag from docker, which still gave me the first error message above. I also tried patching in [these changes](https://github.com/onc-healthit/inferno-program/pull/285/files) from inferno program edition because it seemed related. I still got the second error message below when using the latest version with that patch from Inferno Program Edition.

[logs2.txt](https://github.com/onc-healthit/inferno/files/6534348/logs2.txt)

**Comment by Jammjammjamm** [comment]
This should be resolved by the 2.13.0 release. Please reopen this issue if it remains a problem.
