### ISSUE TITLE
USCPROV-03 thinks "This server does not support Provenance search,read operation(s)" while it does

### ISSUE THREAD

**Issue by msklvsk** [onc-healthit/inferno#571]
**Subject of the issue**
USCPROV-03 reports that _"This server does not support Provenance search,read operation(s) according to conformance statement."_ while there are corresponding entries in the conformance statement.
```json
                {
                    "type": "Provenance",
                    "supportedProfile": ["http://hl7.org/fhir/us/core/StructureDefinition/us-core-provenance"],
                    "interaction": [
                        {
                            "code": "read"
                        },
                        {
                            "code": "search-type"
                        }
                    ],
                    "searchParam": [
                        {
                            "name": "target",
                            "type": "reference"
                        }
                    ]
                }
```

**Your environment**
* Edition of inferno (Community or Program): Community
* Version of inferno: 2.13.0-dev
* Which browser and version(s) is the bug present on?: Chrome 91.0.4472.77

**Steps to reproduce**
Have the above Provenance resource description in your conformance statement, run all tests.

**Expected behavior**
USCPROV-03 does not short-circuit on "This server does not support Provenance search…"

**Actual behavior**
It does.

**Comment by yunwwang** [comment]
Hello @msklvsk : Are you using the inferno-qa.healthit.gov or your own dev deployment from github?

**Comment by msklvsk** [comment]
I’m getting this for both https://inferno.healthit.gov/community (version 2.11.0) and local git revision d5d9b97d16d9a57d1429beefd840f40c9e0d1036 (version 2.13.0-dev).

**Comment by yunwwang** [comment]
Can you save the testing session on the community server? There is a "Save" button on the top right corner.
![image](https://user-images.githubusercontent.com/8761175/121917402-b4138300-ccfa-11eb-9c3e-1f0148681578.png)

**Comment by msklvsk** [comment]
Yet another false alarm from me. I assumed the Run All button would pick up the updated CapabilityStatement (with `{ "code": "search-type" }` for Provenance), however, a clean run was required to make the error disappear.
