### ISSUE TITLE
inferno jwks keys support only key_ops and does not include use=sig

### ISSUE THREAD

**Issue by sagarshah1983** [onc-healthit/inferno#584]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
We are using one of the open source Open ID implementation, which uses the parameter "use" in jwks keys as per specs (Ref: https://datatracker.ietf.org/doc/html/rfc7517#section-4.2)
public keys it generate and it expects is required to have **use** property with value as **sig**
As per Open ID spec we could either use key_ops or use property  and if we want to use both, then both values should be consistent.

Extract from specs
```
   The "use" and "key_ops" JWK members SHOULD NOT be used together;
   however, if both are used, the information they convey MUST be
   consistent.  Applications should specify which of these members they
   use, if either is to be used by the application.
```

**Your environment**
* Edition of inferno (Community or Program): Program
* Version of inferno:1.6.1
* Which browser and version(s) is the bug present on?: Chrome

**Steps to reproduce**
Access inferno url: 
- https://inferno.healthit.gov/inferno
- Go to multi patient API
- Click Run Tests
- View the inferno jwk set url and Open that url in different browser window/tab

Note that this url only contains key_ops parameter. Can it include "use" parameter as well to make this work with those OpenID providers that supports **use** property. 

Include:

* The selected test suite: https://inferno.healthit.gov/inferno/a3ZLpXRk45u/test_sets/test_procedure/#MultiPatientAuthorizationandAPI/test_procedure_MultiPatientAuthorizationandAPI_BulkDataAuthorizationSequence
* The URL of the FHIR server being tested: https://fhir-qa-1.test.yourcareuniverse.net/tenant/7db7dfb5-2f73-4b96-bcf1-131410518850
* The Test ID, if it's a problem with a specific test: BDA-07
* Any required configuration options (client ID, client secret, etc.): Bulk Data Client ID: 31386382-2423-4116-a7bd-1af1c94c144b
* Anything else needed to make the issue occur: Backend services Token endpoint: https://idp-qa-1.test.yourcareuniverse.net/oauth2/token

**Expected behavior**
public keys of inferno should support additional property "use": "sig" as well in addition to key_ops property so that it can work with every OpenID connect provider that works with "use" property.

**Actual behavior**
Call fails with the following error 
```
{
  "error": "invalid_request",
  "error_description": "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Unable to find ECDSA public key with use='sig' for kid '4b49a739d1eb115b3225f4cf9beb6d1b' in JSON Web Key Set."
}
```

Please clarify and suggest your views.

Appreciate!

Regards,
Sagar

**Comment by yunwwang** [comment]
As discussed this [thread](https://chat.fhir.org/#narrow/stream/179170-smart/topic/Backend.20Services.20-.20Public.20keys) on chat.fhir.org
'"use": "sig"` is optional so the authorization server should be able to accept public key with or without that value. 
Inferno tries to create a minimum set of properties required by standard.

**Comment by yunwwang** [comment]
This is repository for Inferno Community but the concern relates to Inferno Program so I duplicate the issue to Inferno Program
https://github.com/onc-healthit/inferno-program/issues/344
