### ISSUE TITLE
Where did "ValueSet-procedure-icd10pcs" come from

### ISSUE THREAD

**Issue by jmandel** [onc-healthit/inferno#79]
I'm trying to track down the source of https://github.com/siteadmin/inferno/blob/master/resources/argonauts/ValueSet-procedure-icd10pcs.json -- specifically, "http://www.icd10data.com/icd10pcs" isn't how FHIR refers to ICD-10, and I'd like to track this down and see if we could get it fixed.

**Comment by arscan** [comment]
I believe we grabbed it from the [ValueSets list in Argonaut DQ IG](https://www.fhir.org/guides/argonaut/r2/valuesets.html) which has an entry for [Argonaut Procedure Type ICD-10-PCS Codes](https://www.fhir.org/guides/argonaut/r2/ValueSet-procedure-icd10pcs.html).

**Comment by yunwwang** [comment]
question was answered
